language: csharp
dotnet: 2.1.4

env:
  - FrameworkPathOverride=/usr/lib/mono/4.5/

jobs:
  include:
    - stage: test
      mono: none
      script:
        - dotnet build ./ISOv4Plugin.sln -c Release -f netstandard2.0
    - stage: deploy
      if: tag =~ ^v\d+\.\d+\.\d+
      mono: 5.8.0
      script:
        - VERSION=$(echo $TRAVIS_TAG | grep -i -P -o '(?<=^v)\d+\.\d+\.\d+(?:.+)?$'); VERSION_NUMBER=$(echo $VERSION | grep -i -P -o '^\d+\.\d+\.\d+')
        - dotnet build ./ISOv4Plugin.sln -c Release /p:Version=$VERSION /p:FileVersion=$VERSION_NUMBER.$TRAVIS_BUILD_NUMBER
        - mkdir -p ./dist; nuget pack ./AgGatewayISOv4Plugin.nuspec -verbosity detailed -outputdirectory ./dist -version $VERSION
        - if [ -n "${NUGET_API_KEY}" ]; then nuget push ./dist/AgGatewayISOv4Plugin.${VERSION}.nupkg -apikey $NUGET_API_KEY -source https://api.nuget.org/v3/index.json; fi
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        file: "./dist/AgGatewayISOv4Plugin.${VERSION}.nupkg"
        skip_cleanup: true
        on:
          tags: true
