//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISOv4PluginTest.TestData {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ISOv4PluginTest.TestData.TestData", typeof(TestData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] NoWorkersPresent {
            get {
                object obj = ResourceManager.GetObject("NoWorkersPresent", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] WorkersWithAllData {
            get {
                object obj = ResourceManager.GetObject("WorkersWithAllData", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;ISO11783_TaskData VersionMajor=&quot;4&quot; VersionMinor=&quot;0&quot; ManagementSoftwareManufacturer=&quot;AgGateway&quot; ManagementSoftwareVersion=&quot;1.0&quot;&gt;
        ///  &lt;WKR A=&quot;WKR1&quot; B=&quot;last&quot; C=&quot;first&quot; D=&quot;line&quot; E=&quot;po box&quot; F=&quot;postal code&quot; G=&quot;city&quot; H=&quot;state&quot; I=&quot;country&quot; J=&quot;Fixed&quot; K=&quot;Mobile&quot; L=&quot;Fax&quot; M=&quot;Email&quot; /&gt;
        ///  &lt;WKR A=&quot;WKR2&quot; B=&quot;last2&quot; C=&quot;first2&quot; D=&quot;line2&quot; E=&quot;po box2&quot; F=&quot;postal code2&quot; G=&quot;city2&quot; H=&quot;state2&quot; I=&quot;country2&quot; J=&quot;Fixed2&quot; K=&quot;Mobile2&quot; L=&quot;Fax2&quot; M=&quot;Email2&quot; /&gt;
        ///&lt;/ISO11783_TaskData&gt;.
        /// </summary>
        internal static string WorkersWithAllDataOutput {
            get {
                return ResourceManager.GetString("WorkersWithAllDataOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] WorkersWithNoContacts {
            get {
                object obj = ResourceManager.GetObject("WorkersWithNoContacts", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;ISO11783_TaskData VersionMajor=&quot;4&quot; VersionMinor=&quot;0&quot; ManagementSoftwareManufacturer=&quot;AgGateway&quot; ManagementSoftwareVersion=&quot;1.0&quot;&gt;
        ///  &lt;WKR A=&quot;WKR1&quot; B=&quot;last&quot; C=&quot;first&quot; /&gt;
        ///  &lt;WKR A=&quot;WKR2&quot; B=&quot;last2&quot; C=&quot;first2&quot; /&gt;
        ///  &lt;WKR A=&quot;WKR3&quot; B=&quot;last3&quot; C=&quot;first3&quot; /&gt;
        ///&lt;/ISO11783_TaskData&gt;.
        /// </summary>
        internal static string WorkersWithNoContactsOutput {
            get {
                return ResourceManager.GetString("WorkersWithNoContactsOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ZeroWorkersPresent {
            get {
                object obj = ResourceManager.GetObject("ZeroWorkersPresent", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
