//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISOv4PluginTest.TestData {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ISOv4PluginTest.TestData.TestData", typeof(TestData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AllPatterns {
            get {
                object obj = ResourceManager.GetObject("AllPatterns", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;ISO11783_TaskData VersionMajor=&quot;4&quot; VersionMinor=&quot;0&quot; ManagementSoftwareManufacturer=&quot;AgGateway&quot; ManagementSoftwareVersion=&quot;1.0&quot;&gt;
        ///  &lt;PFD A=&quot;PFD1&quot; C=&quot;Field&quot; D=&quot;0&quot;&gt;
        ///    &lt;GGP A=&quot;GGP1&quot; B=&quot;guidance group&quot;&gt;
        ///      &lt;GPN A=&quot;GPN1&quot; B=&quot;AbLine&quot; C=&quot;1&quot; E=&quot;1&quot;&gt;
        ///        &lt;LSG A=&quot;5&quot;&gt;
        ///          &lt;PNT A=&quot;2&quot; B=&quot;start&quot; C=&quot;2&quot; D=&quot;1&quot; /&gt;
        ///          &lt;PNT A=&quot;2&quot; B=&quot;end&quot; C=&quot;4&quot; D=&quot;3&quot; /&gt;
        ///        &lt;/LSG&gt;
        ///        &lt;PLN A=&quot;1&quot;&gt;
        ///          &lt;LSG A=&quot;1&quot;&gt;
        ///            &lt;PNT A=&quot;2&quot; B=&quot;start&quot; C=&quot;2&quot; D=&quot;1&quot; /&gt;
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AllPatternsOutput {
            get {
                return ResourceManager.GetString("AllPatternsOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GroupsNoPatternsOrBoundary {
            get {
                object obj = ResourceManager.GetObject("GroupsNoPatternsOrBoundary", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;ISO11783_TaskData VersionMajor=&quot;4&quot; VersionMinor=&quot;0&quot; ManagementSoftwareManufacturer=&quot;AgGateway&quot; ManagementSoftwareVersion=&quot;1.0&quot;&gt;
        ///  &lt;PFD A=&quot;PFD1&quot; C=&quot;Field&quot; D=&quot;0&quot;&gt;
        ///    &lt;GGP A=&quot;GGP1&quot; B=&quot;guidance group 1&quot; /&gt;
        ///    &lt;GGP A=&quot;GGP2&quot; B=&quot;guidance group 2&quot; /&gt;
        ///    &lt;GGP A=&quot;GGP3&quot; B=&quot;guidance group 3&quot; /&gt;
        ///  &lt;/PFD&gt;
        ///&lt;/ISO11783_TaskData&gt;.
        /// </summary>
        internal static string GroupsNoPatternsOrBoundaryOutput {
            get {
                return ResourceManager.GetString("GroupsNoPatternsOrBoundaryOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GroupsWithBoundaryAndNoPatterns {
            get {
                object obj = ResourceManager.GetObject("GroupsWithBoundaryAndNoPatterns", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;ISO11783_TaskData VersionMajor=&quot;4&quot; VersionMinor=&quot;0&quot; ManagementSoftwareManufacturer=&quot;AgGateway&quot; ManagementSoftwareVersion=&quot;1.0&quot;&gt;
        ///  &lt;PFD A=&quot;PFD1&quot; C=&quot;Field&quot; D=&quot;0&quot;&gt;
        ///    &lt;GGP A=&quot;GGP1&quot; B=&quot;guidance group 1&quot;&gt;
        ///      &lt;PLN A=&quot;1&quot;&gt;
        ///        &lt;LSG A=&quot;1&quot;&gt;
        ///          &lt;PNT A=&quot;2&quot; B=&quot;start&quot; C=&quot;2&quot; D=&quot;1&quot; /&gt;
        ///        &lt;/LSG&gt;
        ///      &lt;/PLN&gt;
        ///    &lt;/GGP&gt;
        ///    &lt;GGP A=&quot;GGP2&quot; B=&quot;guidance group 2&quot;&gt;
        ///      &lt;PLN A=&quot;1&quot;&gt;
        ///        &lt;LSG A=&quot;1&quot;&gt;
        ///          &lt;PNT A=&quot;2&quot; B=&quot;start&quot; C=&quot;20&quot; D=&quot;10&quot; /&gt;
        ///        [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GroupsWithBoundaryAndNoPatternsOutput {
            get {
                return ResourceManager.GetString("GroupsWithBoundaryAndNoPatternsOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GroupsWithBoundaryAndPatterns {
            get {
                object obj = ResourceManager.GetObject("GroupsWithBoundaryAndPatterns", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;ISO11783_TaskData VersionMajor=&quot;4&quot; VersionMinor=&quot;0&quot; ManagementSoftwareManufacturer=&quot;AgGateway&quot; ManagementSoftwareVersion=&quot;1.0&quot;&gt;
        ///  &lt;PFD A=&quot;PFD1&quot; C=&quot;Field&quot; D=&quot;0&quot;&gt;
        ///    &lt;GGP A=&quot;GGP1&quot; B=&quot;guidance group 1&quot;&gt;
        ///      &lt;GPN A=&quot;GPN1&quot; B=&quot;AbLine&quot; C=&quot;1&quot; E=&quot;1&quot;&gt;
        ///        &lt;LSG A=&quot;5&quot;&gt;
        ///          &lt;PNT A=&quot;2&quot; B=&quot;start&quot; C=&quot;2&quot; D=&quot;1&quot; /&gt;
        ///          &lt;PNT A=&quot;2&quot; B=&quot;end&quot; C=&quot;4&quot; D=&quot;3&quot; /&gt;
        ///        &lt;/LSG&gt;
        ///        &lt;PLN A=&quot;1&quot;&gt;
        ///          &lt;LSG A=&quot;1&quot;&gt;
        ///            &lt;PNT A=&quot;2&quot; B=&quot;start&quot; C=&quot;21&quot; D=&quot;11&quot; / [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GroupsWithBoundaryAndPatternsOutput {
            get {
                return ResourceManager.GetString("GroupsWithBoundaryAndPatternsOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MissingUnit {
            get {
                object obj = ResourceManager.GetObject("MissingUnit", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;TZN A=&quot;1&quot; B=&quot;zone1&quot;&gt;
        ///  &lt;PDV A=&quot;0006&quot; B=&quot;100&quot; C=&quot;PDT1&quot; /&gt;
        ///&lt;/TZN&gt;.
        /// </summary>
        internal static string MissingUnitOutput {
            get {
                return ResourceManager.GetString("MissingUnitOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MultipleVariables {
            get {
                object obj = ResourceManager.GetObject("MultipleVariables", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;TZN A=&quot;1&quot; B=&quot;zone1&quot;&gt;
        ///  &lt;PDV A=&quot;0006&quot; B=&quot;10000&quot; C=&quot;PDT1&quot; /&gt;
        ///  &lt;PDV A=&quot;0001&quot; B=&quot;2000000&quot; C=&quot;PDT2&quot; /&gt;
        ///  &lt;PDV A=&quot;0029&quot; B=&quot;300000&quot; C=&quot;PDT3&quot; /&gt;
        ///&lt;/TZN&gt;.
        /// </summary>
        internal static string MultipleVariablesOutput {
            get {
                return ResourceManager.GetString("MultipleVariablesOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] NoVariables {
            get {
                object obj = ResourceManager.GetObject("NoVariables", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;TZN A=&quot;1&quot; B=&quot;zone1&quot; /&gt;.
        /// </summary>
        internal static string NoVariablesOutput {
            get {
                return ResourceManager.GetString("NoVariablesOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] NoWorkersPresent {
            get {
                object obj = ResourceManager.GetObject("NoWorkersPresent", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SingleProduct {
            get {
                object obj = ResourceManager.GetObject("SingleProduct", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 010000000200000003000000040000000500000006000000070000000800000009000000.
        /// </summary>
        internal static string SingleProductOutputTxt {
            get {
                return ResourceManager.GetString("SingleProductOutputTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;ISO11783_TaskData VersionMajor=&quot;4&quot; VersionMinor=&quot;0&quot; ManagementSoftwareManufacturer=&quot;AgGateway&quot; ManagementSoftwareVersion=&quot;1.0&quot;&gt;
        ///  &lt;PDT A=&quot;PDT1&quot; B=&quot;product&quot; /&gt;
        ///  &lt;TSK A=&quot;TSK1&quot; B=&quot;test&quot; G=&quot;1&quot;&gt;
        ///    &lt;TZN A=&quot;1&quot; B=&quot;Default&quot;&gt;
        ///      &lt;PDV A=&quot;0006&quot; B=&quot;0&quot; C=&quot;PDT1&quot; /&gt;
        ///    &lt;/TZN&gt;
        ///    &lt;GRD A=&quot;2&quot; B=&quot;1&quot; C=&quot;0.00020000000000&quot; D=&quot;0.00010000000000&quot; E=&quot;3&quot; F=&quot;3&quot; G=&quot;GRD00000&quot; I=&quot;2&quot; J=&quot;1&quot; /&gt;
        ///  &lt;/TSK&gt;
        ///&lt;/ISO11783_TaskData&gt;.
        /// </summary>
        internal static string SingleProductOutputXml {
            get {
                return ResourceManager.GetString("SingleProductOutputXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] UnsupportedUnitDimension {
            get {
                object obj = ResourceManager.GetObject("UnsupportedUnitDimension", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;TZN A=&quot;1&quot; B=&quot;zone1&quot;&gt;
        ///  &lt;PDV A=&quot;0006&quot; B=&quot;10000&quot; C=&quot;PDT1&quot; /&gt;
        ///&lt;/TZN&gt;.
        /// </summary>
        internal static string UnsupportedUnitDimensionOutput {
            get {
                return ResourceManager.GetString("UnsupportedUnitDimensionOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] WorkersWithAllData {
            get {
                object obj = ResourceManager.GetObject("WorkersWithAllData", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;ISO11783_TaskData VersionMajor=&quot;4&quot; VersionMinor=&quot;0&quot; ManagementSoftwareManufacturer=&quot;AgGateway&quot; ManagementSoftwareVersion=&quot;1.0&quot;&gt;
        ///  &lt;WKR A=&quot;WKR1&quot; B=&quot;last&quot; C=&quot;first&quot; D=&quot;line&quot; E=&quot;po box&quot; F=&quot;postal code&quot; G=&quot;city&quot; H=&quot;state&quot; I=&quot;country&quot; J=&quot;Fixed&quot; K=&quot;Mobile&quot; L=&quot;Fax&quot; M=&quot;Email&quot; /&gt;
        ///  &lt;WKR A=&quot;WKR2&quot; B=&quot;last2&quot; C=&quot;first2&quot; D=&quot;line2&quot; E=&quot;po box2&quot; F=&quot;postal code2&quot; G=&quot;city2&quot; H=&quot;state2&quot; I=&quot;country2&quot; J=&quot;Fixed2&quot; K=&quot;Mobile2&quot; L=&quot;Fax2&quot; M=&quot;Email2&quot; /&gt;
        ///&lt;/ISO11783_TaskData&gt;.
        /// </summary>
        internal static string WorkersWithAllDataOutput {
            get {
                return ResourceManager.GetString("WorkersWithAllDataOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] WorkersWithNoContacts {
            get {
                object obj = ResourceManager.GetObject("WorkersWithNoContacts", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;ISO11783_TaskData VersionMajor=&quot;4&quot; VersionMinor=&quot;0&quot; ManagementSoftwareManufacturer=&quot;AgGateway&quot; ManagementSoftwareVersion=&quot;1.0&quot;&gt;
        ///  &lt;WKR A=&quot;WKR1&quot; B=&quot;last&quot; C=&quot;first&quot; /&gt;
        ///  &lt;WKR A=&quot;WKR2&quot; B=&quot;last2&quot; C=&quot;first2&quot; /&gt;
        ///  &lt;WKR A=&quot;WKR3&quot; B=&quot;last3&quot; C=&quot;first3&quot; /&gt;
        ///&lt;/ISO11783_TaskData&gt;.
        /// </summary>
        internal static string WorkersWithNoContactsOutput {
            get {
                return ResourceManager.GetString("WorkersWithNoContactsOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ZeroWorkersPresent {
            get {
                object obj = ResourceManager.GetObject("ZeroWorkersPresent", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
