//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISOv4PluginTest.TestData {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ISOv4PluginTest.TestData.TestData", typeof(TestData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AllPatterns {
            get {
                object obj = ResourceManager.GetObject("AllPatterns", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ISO11783_TaskData VersionMajor=&quot;4&quot; VersionMinor=&quot;0&quot; ManagementSoftwareManufacturer=&quot;AgGateway&quot; ManagementSoftwareVersion=&quot;1.0&quot; DataTransferOrigin=&quot;1&quot; TaskControllerManufacturer=&quot;&quot; TaskControllerVersion=&quot;&quot;&gt;
        ///  &lt;PFD A=&quot;PFD0&quot; C=&quot;Field&quot; D=&quot;0&quot;&gt;
        ///    &lt;GGP A=&quot;GGP0&quot; B=&quot;guidance group&quot;&gt;
        ///      &lt;GPN A=&quot;GPN0&quot; B=&quot;AbLine&quot; C=&quot;1&quot; E=&quot;1&quot;&gt;
        ///        &lt;LSG A=&quot;5&quot;&gt;
        ///          &lt;PNT A=&quot;2&quot; B=&quot;start&quot; C=&quot;2&quot; D=&quot;1&quot; /&gt;
        ///          &lt;PNT A=&quot;2&quot; B=&quot;end&quot; C=&quot;4&quot; D=&quot;3&quot; /&gt;
        ///        &lt;/LSG&gt;
        ///        &lt;PLN A=&quot;1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AllPatternsOutput {
            get {
                return ResourceManager.GetString("AllPatternsOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;XFC&gt;
        ///  &lt;CCT A=&quot;CCT2&quot; B=&quot;Comment 2&quot; C=&quot;2&quot;&gt;
        ///    &lt;CCL A=&quot;CCL3&quot; B=&quot;Comment value 3&quot; /&gt;
        ///    &lt;CCL A=&quot;CCL4&quot; B=&quot;Comment value 4&quot; /&gt;
        ///  &lt;/CCT&gt;
        ///&lt;/XFC&gt;.
        /// </summary>
        internal static string CCT00002 {
            get {
                return ResourceManager.GetString("CCT00002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;ISO11783_TaskData TaskControllerVersion=&quot;&quot;
        ///                   VersionMinor=&quot;1&quot;
        ///                   ManagementSoftwareManufacturer=&quot;Topcon Precision Agriculture&quot;
        ///                   DataTransferOrigin=&quot;2&quot;
        ///                   ManagementSoftwareVersion=&quot;1.0&quot;
        ///                   TaskControllerManufacturer=&quot;&quot;
        ///                   VersionMajor=&quot;4&quot; &gt;
        ///
        ///  &lt;CCT A=&quot;CCT1&quot; B=&quot;Comment 1&quot; C=&quot;2&quot;&gt;
        ///    &lt;CCL A=&quot;CCL1&quot; B=&quot;Comment value 1&quot; /&gt;
        ///    &lt;CCL A=&quot;CCL2&quot; B=&quot;Comment value 2&quot; /&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Comment1 {
            get {
                return ResourceManager.GetString("Comment1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;ISO11783_TaskData TaskControllerVersion=&quot;&quot;
        ///                   VersionMinor=&quot;1&quot;
        ///                   ManagementSoftwareManufacturer=&quot;Topcon Precision Agriculture&quot;
        ///                   DataTransferOrigin=&quot;2&quot;
        ///                   ManagementSoftwareVersion=&quot;1.0&quot;
        ///                   TaskControllerManufacturer=&quot;&quot;
        ///                   VersionMajor=&quot;4&quot; &gt;
        ///
        ///  &lt;CCT A=&quot;CCT1&quot; B=&quot;Comment 1&quot; C=&quot;-1&quot;&gt;
        ///    &lt;CCL A=&quot;CCL1&quot; B=&quot;Comment value 1&quot; /&gt;
        ///    &lt;CCL A=&quot;CCL2&quot; B=&quot;Comment value 2&quot; /&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Comment10 {
            get {
                return ResourceManager.GetString("Comment10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;ISO11783_TaskData TaskControllerVersion=&quot;&quot;
        ///                   VersionMinor=&quot;1&quot;
        ///                   ManagementSoftwareManufacturer=&quot;Topcon Precision Agriculture&quot;
        ///                   DataTransferOrigin=&quot;2&quot;
        ///                   ManagementSoftwareVersion=&quot;1.0&quot;
        ///                   TaskControllerManufacturer=&quot;&quot;
        ///                   VersionMajor=&quot;4&quot; &gt;
        ///
        ///  &lt;CCT A=&quot;CCT1&quot; B=&quot;Comment 1&quot; C=&quot;2&quot;&gt;
        ///    &lt;CCL A=&quot;CCL1&quot; B=&quot;Comment value 1&quot; /&gt;
        ///    &lt;CCL A=&quot;CCL2&quot; B=&quot;Comment value 2&quot; /&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Comment2 {
            get {
                return ResourceManager.GetString("Comment2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;ISO11783_TaskData TaskControllerVersion=&quot;&quot;
        ///                   VersionMinor=&quot;1&quot;
        ///                   ManagementSoftwareManufacturer=&quot;Topcon Precision Agriculture&quot;
        ///                   DataTransferOrigin=&quot;2&quot;
        ///                   ManagementSoftwareVersion=&quot;1.0&quot;
        ///                   TaskControllerManufacturer=&quot;&quot;
        ///                   VersionMajor=&quot;4&quot; &gt;
        ///
        ///  &lt;CCT B=&quot;Comment 1&quot; C=&quot;2&quot;&gt;
        ///    &lt;CCL A=&quot;CCL1&quot; B=&quot;Comment value 1&quot; /&gt;
        ///    &lt;CCL A=&quot;CCL2&quot; B=&quot;Comment value 2&quot; /&gt;
        ///  &lt;/CCT&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Comment3 {
            get {
                return ResourceManager.GetString("Comment3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;ISO11783_TaskData TaskControllerVersion=&quot;&quot;
        ///                   VersionMinor=&quot;1&quot;
        ///                   ManagementSoftwareManufacturer=&quot;Topcon Precision Agriculture&quot;
        ///                   DataTransferOrigin=&quot;2&quot;
        ///                   ManagementSoftwareVersion=&quot;1.0&quot;
        ///                   TaskControllerManufacturer=&quot;&quot;
        ///                   VersionMajor=&quot;4&quot; &gt;
        ///
        ///  &lt;CCT A=&quot;CCT1&quot; C=&quot;2&quot;&gt;
        ///    &lt;CCL A=&quot;CCL1&quot; B=&quot;Comment value 1&quot; /&gt;
        ///    &lt;CCL A=&quot;CCL2&quot; B=&quot;Comment value 2&quot; /&gt;
        ///  &lt;/CCT&gt;
        ///          /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Comment4 {
            get {
                return ResourceManager.GetString("Comment4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;ISO11783_TaskData TaskControllerVersion=&quot;&quot;
        ///                   VersionMinor=&quot;1&quot;
        ///                   ManagementSoftwareManufacturer=&quot;Topcon Precision Agriculture&quot;
        ///                   DataTransferOrigin=&quot;2&quot;
        ///                   ManagementSoftwareVersion=&quot;1.0&quot;
        ///                   TaskControllerManufacturer=&quot;&quot;
        ///                   VersionMajor=&quot;4&quot; &gt;
        ///
        ///  &lt;CCT A=&quot;CCT1&quot; B=&quot;Comment 1&quot;&gt;
        ///    &lt;CCL A=&quot;CCL1&quot; B=&quot;Comment value 1&quot; /&gt;
        ///    &lt;CCL A=&quot;CCL2&quot; B=&quot;Comment value 2&quot; /&gt;
        ///  &lt;/C [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Comment5 {
            get {
                return ResourceManager.GetString("Comment5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;ISO11783_TaskData TaskControllerVersion=&quot;&quot;
        ///                   VersionMinor=&quot;1&quot;
        ///                   ManagementSoftwareManufacturer=&quot;Topcon Precision Agriculture&quot;
        ///                   DataTransferOrigin=&quot;2&quot;
        ///                   ManagementSoftwareVersion=&quot;1.0&quot;
        ///                   TaskControllerManufacturer=&quot;&quot;
        ///                   VersionMajor=&quot;4&quot; &gt;
        ///
        ///  &lt;CCT A=&quot;CCT1&quot; B=&quot;Comment 1&quot; C=&quot;2&quot;&gt;
        ///  &lt;/CCT&gt;
        ///
        ///&lt;/ISO11783_TaskData&gt;.
        /// </summary>
        internal static string Comment6 {
            get {
                return ResourceManager.GetString("Comment6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;ISO11783_TaskData TaskControllerVersion=&quot;&quot;
        ///                   VersionMinor=&quot;1&quot;
        ///                   ManagementSoftwareManufacturer=&quot;Topcon Precision Agriculture&quot;
        ///                   DataTransferOrigin=&quot;2&quot;
        ///                   ManagementSoftwareVersion=&quot;1.0&quot;
        ///                   TaskControllerManufacturer=&quot;&quot;
        ///                   VersionMajor=&quot;4&quot; &gt;
        ///
        ///  &lt;CCT A=&quot;CCT1&quot; B=&quot;Comment 1&quot; C=&quot;6&quot;&gt;
        ///    &lt;CCL A=&quot;CCL1&quot; B=&quot;Comment value 1&quot; /&gt;
        ///    &lt;CCL A=&quot;CCL2&quot; B=&quot;Comment value 2&quot; /&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Comment7 {
            get {
                return ResourceManager.GetString("Comment7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;ISO11783_TaskData TaskControllerVersion=&quot;&quot;
        ///                   VersionMinor=&quot;1&quot;
        ///                   ManagementSoftwareManufacturer=&quot;Topcon Precision Agriculture&quot;
        ///                   DataTransferOrigin=&quot;2&quot;
        ///                   ManagementSoftwareVersion=&quot;1.0&quot;
        ///                   TaskControllerManufacturer=&quot;&quot;
        ///                   VersionMajor=&quot;4&quot; &gt;
        ///
        ///  &lt;CCT A=&quot;CCT1&quot; B=&quot;Comment 1&quot; C=&quot;&quot;&gt;
        ///    &lt;CCL A=&quot;CCL1&quot; B=&quot;Comment value 1&quot; /&gt;
        ///    &lt;CCL A=&quot;CCL2&quot; B=&quot;Comment value 2&quot; /&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Comment8 {
            get {
                return ResourceManager.GetString("Comment8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;ISO11783_TaskData TaskControllerVersion=&quot;&quot;
        ///                   VersionMinor=&quot;1&quot;
        ///                   ManagementSoftwareManufacturer=&quot;Topcon Precision Agriculture&quot;
        ///                   DataTransferOrigin=&quot;2&quot;
        ///                   ManagementSoftwareVersion=&quot;1.0&quot;
        ///                   TaskControllerManufacturer=&quot;&quot;
        ///                   VersionMajor=&quot;4&quot; &gt;
        ///
        ///  &lt;CCT A=&quot;CCT1&quot; B=&quot;Comment 1&quot; C=&quot;2&quot;&gt;
        ///    &lt;CCL A=&quot;CCL1&quot; B=&quot;&quot; /&gt;
        ///    &lt;CCL A=&quot;CCL1&quot; /&gt;
        ///    &lt;CCL A=&quot;&quot; B=&quot;Comment value 2&quot;/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Comment9 {
            get {
                return ResourceManager.GetString("Comment9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;ISO11783_TaskData TaskControllerVersion=&quot;&quot;
        ///                   VersionMinor=&quot;1&quot;
        ///                   ManagementSoftwareManufacturer=&quot;Topcon Precision Agriculture&quot;
        ///                   DataTransferOrigin=&quot;2&quot;
        ///                   ManagementSoftwareVersion=&quot;1.0&quot;
        ///                   TaskControllerManufacturer=&quot;&quot;
        ///                   VersionMajor=&quot;4&quot; &gt;
        ///
        ///  &lt;CTP A=&quot;CTP1&quot; B=&quot;Crop 1&quot; &gt;
        ///    &lt;CVT A=&quot;CVT1&quot; B=&quot;Variety 1&quot; /&gt;
        ///    &lt;CVT A=&quot;CVT2&quot; B=&quot;Variety 2&quot; /&gt;
        ///  &lt;/CTP&gt;
        ///  
        ///&lt;/ISO [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Crop1 {
            get {
                return ResourceManager.GetString("Crop1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;ISO11783_TaskData TaskControllerVersion=&quot;&quot;
        ///                   VersionMinor=&quot;1&quot;
        ///                   ManagementSoftwareManufacturer=&quot;Topcon Precision Agriculture&quot;
        ///                   DataTransferOrigin=&quot;2&quot;
        ///                   ManagementSoftwareVersion=&quot;1.0&quot;
        ///                   TaskControllerManufacturer=&quot;&quot;
        ///                   VersionMajor=&quot;4&quot; &gt;
        ///
        ///  &lt;CTP A=&quot;CTP1&quot; B=&quot;Crop 1&quot; /&gt;  
        ///&lt;/ISO11783_TaskData&gt;.
        /// </summary>
        internal static string Crop2 {
            get {
                return ResourceManager.GetString("Crop2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;ISO11783_TaskData TaskControllerVersion=&quot;&quot;
        ///                   VersionMinor=&quot;1&quot;
        ///                   ManagementSoftwareManufacturer=&quot;Topcon Precision Agriculture&quot;
        ///                   DataTransferOrigin=&quot;2&quot;
        ///                   ManagementSoftwareVersion=&quot;1.0&quot;
        ///                   TaskControllerManufacturer=&quot;&quot;
        ///                   VersionMajor=&quot;4&quot; &gt;
        ///
        ///  &lt;CTP A=&quot;CTP1&quot; B=&quot;Crop 1&quot;&gt;
        ///    &lt;CVT A=&quot;CVT1&quot; B=&quot;Variety 1&quot; /&gt;
        ///    &lt;CVT A=&quot;CVT2&quot; B=&quot;Variety 2&quot; /&gt;
        ///  &lt;/CTP&gt;
        ///
        ///  &lt;XFR A [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Crop3 {
            get {
                return ResourceManager.GetString("Crop3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;ISO11783_TaskData TaskControllerVersion=&quot;&quot;
        ///                   VersionMinor=&quot;1&quot;
        ///                   ManagementSoftwareManufacturer=&quot;Topcon Precision Agriculture&quot;
        ///                   DataTransferOrigin=&quot;2&quot;
        ///                   ManagementSoftwareVersion=&quot;1.0&quot;
        ///                   TaskControllerManufacturer=&quot;&quot;
        ///                   VersionMajor=&quot;4&quot; &gt;
        ///
        ///  &lt;CTP A=&quot;CTP1&quot; /&gt;
        ///  
        ///&lt;/ISO11783_TaskData&gt;.
        /// </summary>
        internal static string Crop4 {
            get {
                return ResourceManager.GetString("Crop4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;ISO11783_TaskData TaskControllerVersion=&quot;&quot;
        ///                   VersionMinor=&quot;1&quot;
        ///                   ManagementSoftwareManufacturer=&quot;Topcon Precision Agriculture&quot;
        ///                   DataTransferOrigin=&quot;2&quot;
        ///                   ManagementSoftwareVersion=&quot;1.0&quot;
        ///                   TaskControllerManufacturer=&quot;&quot;
        ///                   VersionMajor=&quot;4&quot; &gt;
        ///
        ///  &lt;CTP B=&quot;Crop&quot; /&gt;
        ///  
        ///&lt;/ISO11783_TaskData&gt;.
        /// </summary>
        internal static string Crop5 {
            get {
                return ResourceManager.GetString("Crop5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;ISO11783_TaskData TaskControllerVersion=&quot;&quot;
        ///                   VersionMinor=&quot;1&quot;
        ///                   ManagementSoftwareManufacturer=&quot;Topcon Precision Agriculture&quot;
        ///                   DataTransferOrigin=&quot;2&quot;
        ///                   ManagementSoftwareVersion=&quot;1.0&quot;
        ///                   TaskControllerManufacturer=&quot;&quot;
        ///                   VersionMajor=&quot;4&quot; &gt;
        ///
        ///  &lt;XFR A=&quot;CTP00006&quot; B=&quot;1&quot; /&gt;
        ///
        ///&lt;/ISO11783_TaskData&gt;.
        /// </summary>
        internal static string Crop6 {
            get {
                return ResourceManager.GetString("Crop6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;XFC&gt;
        ///  &lt;CTP A=&quot;CTP2&quot; B=&quot;Crop 2&quot;&gt;
        ///    &lt;CVT A=&quot;CVT3&quot; B=&quot;Variety 3&quot; /&gt;
        ///    &lt;CVT A=&quot;CVT4&quot; B=&quot;Variety 4&quot; /&gt;
        ///  &lt;/CTP&gt;
        ///&lt;/XFC&gt;.
        /// </summary>
        internal static string CTP00003 {
            get {
                return ResourceManager.GetString("CTP00003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;XFC&gt;
        ///  &lt;CTR A=&quot;CTR1&quot; B=&quot;Last1&quot; C=&quot;First1&quot; D=&quot;Street1&quot; E=&quot;PO Box1&quot; F=&quot;PostalCode1&quot; G=&quot;City1&quot; H=&quot;State1&quot; I=&quot;Country1&quot; J=&quot;Phone1&quot; K=&quot;Mobile1&quot; L=&quot;Fax1&quot; M=&quot;Email1&quot;/&gt;
        ///&lt;/XFC&gt;.
        /// </summary>
        internal static string CTR00005 {
            get {
                return ResourceManager.GetString("CTR00005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;ISO11783_TaskData TaskControllerVersion=&quot;&quot;
        ///                   VersionMinor=&quot;1&quot;
        ///                   ManagementSoftwareManufacturer=&quot;Topcon Precision Agriculture&quot;
        ///                   DataTransferOrigin=&quot;2&quot;
        ///                   ManagementSoftwareVersion=&quot;1.0&quot;
        ///                   TaskControllerManufacturer=&quot;&quot;
        ///                   VersionMajor=&quot;4&quot; &gt;
        ///
        ///  &lt;CTR A=&quot;CTR1&quot; B=&quot;Last&quot; C=&quot;First&quot; D=&quot;Street&quot; E=&quot;PO Box&quot; F=&quot;PostalCode&quot; G=&quot;City&quot; H=&quot;State&quot; I=&quot;Country&quot; J=&quot;Phone&quot; K=&quot;Mobil [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Customer1 {
            get {
                return ResourceManager.GetString("Customer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;ISO11783_TaskData TaskControllerVersion=&quot;&quot;
        ///                   VersionMinor=&quot;1&quot;
        ///                   ManagementSoftwareManufacturer=&quot;Topcon Precision Agriculture&quot;
        ///                   DataTransferOrigin=&quot;2&quot;
        ///                   ManagementSoftwareVersion=&quot;1.0&quot;
        ///                   TaskControllerManufacturer=&quot;&quot;
        ///                   VersionMajor=&quot;4&quot; &gt;
        ///
        ///  &lt;CTR A=&quot;CTR1&quot; B=&quot;Last&quot; C=&quot;First&quot; D=&quot;Street&quot; E=&quot;PO Box&quot; F=&quot;PostalCode&quot; G=&quot;City&quot; H=&quot;State&quot; I=&quot;Country&quot;/&gt;
        ///  
        ///&lt;/ISO11783_ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Customer2 {
            get {
                return ResourceManager.GetString("Customer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;ISO11783_TaskData TaskControllerVersion=&quot;&quot;
        ///                   VersionMinor=&quot;1&quot;
        ///                   ManagementSoftwareManufacturer=&quot;Topcon Precision Agriculture&quot;
        ///                   DataTransferOrigin=&quot;2&quot;
        ///                   ManagementSoftwareVersion=&quot;1.0&quot;
        ///                   TaskControllerManufacturer=&quot;&quot;
        ///                   VersionMajor=&quot;4&quot; &gt;
        ///
        ///  &lt;CTR A=&quot;CTR1&quot; B=&quot;Last&quot; C=&quot;First&quot; /&gt;
        ///  
        ///&lt;/ISO11783_TaskData&gt;.
        /// </summary>
        internal static string Customer3 {
            get {
                return ResourceManager.GetString("Customer3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;ISO11783_TaskData TaskControllerVersion=&quot;&quot;
        ///                   VersionMinor=&quot;1&quot;
        ///                   ManagementSoftwareManufacturer=&quot;Topcon Precision Agriculture&quot;
        ///                   DataTransferOrigin=&quot;2&quot;
        ///                   ManagementSoftwareVersion=&quot;1.0&quot;
        ///                   TaskControllerManufacturer=&quot;&quot;
        ///                   VersionMajor=&quot;4&quot; &gt;
        ///
        ///  &lt;CTR A=&quot;CTR1&quot; B=&quot;Last&quot; /&gt;
        ///  
        ///&lt;/ISO11783_TaskData&gt;.
        /// </summary>
        internal static string Customer4 {
            get {
                return ResourceManager.GetString("Customer4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;ISO11783_TaskData TaskControllerVersion=&quot;&quot;
        ///                   VersionMinor=&quot;1&quot;
        ///                   ManagementSoftwareManufacturer=&quot;Topcon Precision Agriculture&quot;
        ///                   DataTransferOrigin=&quot;2&quot;
        ///                   ManagementSoftwareVersion=&quot;1.0&quot;
        ///                   TaskControllerManufacturer=&quot;&quot;
        ///                   VersionMajor=&quot;4&quot; &gt;
        ///
        ///  &lt;XFR A=&quot;CTR00005&quot; B=&quot;1&quot; /&gt;
        ///
        ///  &lt;CTR A=&quot;CTR2&quot; B=&quot;Last2&quot; C=&quot;First2&quot; D=&quot;Street2&quot; E=&quot;PO Box2&quot; F=&quot;PostalCode2&quot; G=&quot;City2&quot; H= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Customer5 {
            get {
                return ResourceManager.GetString("Customer5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;ISO11783_TaskData TaskControllerVersion=&quot;&quot;
        ///                   VersionMinor=&quot;1&quot;
        ///                   ManagementSoftwareManufacturer=&quot;Topcon Precision Agriculture&quot;
        ///                   DataTransferOrigin=&quot;2&quot;
        ///                   ManagementSoftwareVersion=&quot;1.0&quot;
        ///                   TaskControllerManufacturer=&quot;&quot;
        ///                   VersionMajor=&quot;4&quot; &gt;
        ///
        ///  &lt;CTR A=&quot;CTR1&quot;/&gt;
        ///
        ///&lt;/ISO11783_TaskData&gt;.
        /// </summary>
        internal static string Customer6 {
            get {
                return ResourceManager.GetString("Customer6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;ISO11783_TaskData TaskControllerVersion=&quot;&quot;
        ///                   VersionMinor=&quot;1&quot;
        ///                   ManagementSoftwareManufacturer=&quot;Topcon Precision Agriculture&quot;
        ///                   DataTransferOrigin=&quot;2&quot;
        ///                   ManagementSoftwareVersion=&quot;1.0&quot;
        ///                   TaskControllerManufacturer=&quot;&quot;
        ///                   VersionMajor=&quot;4&quot; &gt;
        ///
        ///  &lt;CTR B=&quot;Customer&quot;/&gt;
        ///
        ///&lt;/ISO11783_TaskData&gt;.
        /// </summary>
        internal static string Customer7 {
            get {
                return ResourceManager.GetString("Customer7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;ISO11783_TaskData TaskControllerVersion=&quot;&quot;
        ///                   VersionMinor=&quot;1&quot;
        ///                   ManagementSoftwareManufacturer=&quot;Topcon Precision Agriculture&quot;
        ///                   DataTransferOrigin=&quot;2&quot;
        ///                   ManagementSoftwareVersion=&quot;1.0&quot;
        ///                   TaskControllerManufacturer=&quot;&quot;
        ///                   VersionMajor=&quot;4&quot; &gt;
        ///
        ///  &lt;XFR A=&quot;CTR00008&quot; B=&quot;1&quot; /&gt;
        ///
        ///&lt;/ISO11783_TaskData&gt;.
        /// </summary>
        internal static string Customer8 {
            get {
                return ResourceManager.GetString("Customer8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;ISO11783_TaskData TaskControllerVersion=&quot;&quot;
        ///                   VersionMinor=&quot;1&quot;
        ///                   ManagementSoftwareManufacturer=&quot;Topcon Precision Agriculture&quot;
        ///                   DataTransferOrigin=&quot;2&quot;
        ///                   ManagementSoftwareVersion=&quot;1.0&quot;
        ///                   TaskControllerManufacturer=&quot;&quot;
        ///                   VersionMajor=&quot;4&quot; &gt;
        ///
        ///  &lt;FRM A=&quot;FRM1&quot; B=&quot;Farm&quot; C=&quot;Street&quot; D=&quot;PO Box&quot; E=&quot;PostalCode&quot; F=&quot;City&quot; G=&quot;State&quot; H=&quot;Country&quot; I=&quot;CTR1&quot;/&gt;
        ///
        ///  &lt;CTR A=&quot;CTR1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Farm1 {
            get {
                return ResourceManager.GetString("Farm1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;ISO11783_TaskData TaskControllerVersion=&quot;&quot;
        ///                   VersionMinor=&quot;1&quot;
        ///                   ManagementSoftwareManufacturer=&quot;Topcon Precision Agriculture&quot;
        ///                   DataTransferOrigin=&quot;2&quot;
        ///                   ManagementSoftwareVersion=&quot;1.0&quot;
        ///                   TaskControllerManufacturer=&quot;&quot;
        ///                   VersionMajor=&quot;4&quot; &gt;
        ///
        ///  &lt;FRM A=&quot;FRM1&quot; B=&quot;Farm&quot; I=&quot;CTR1&quot;/&gt;
        ///  
        ///&lt;/ISO11783_TaskData&gt;.
        /// </summary>
        internal static string Farm2 {
            get {
                return ResourceManager.GetString("Farm2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;ISO11783_TaskData TaskControllerVersion=&quot;&quot;
        ///                   VersionMinor=&quot;1&quot;
        ///                   ManagementSoftwareManufacturer=&quot;Topcon Precision Agriculture&quot;
        ///                   DataTransferOrigin=&quot;2&quot;
        ///                   ManagementSoftwareVersion=&quot;1.0&quot;
        ///                   TaskControllerManufacturer=&quot;&quot;
        ///                   VersionMajor=&quot;4&quot; &gt;
        ///
        ///  &lt;FRM A=&quot;FRM1&quot; B=&quot;Farm&quot;/&gt;
        ///  
        ///&lt;/ISO11783_TaskData&gt;.
        /// </summary>
        internal static string Farm3 {
            get {
                return ResourceManager.GetString("Farm3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;ISO11783_TaskData TaskControllerVersion=&quot;&quot;
        ///                   VersionMinor=&quot;1&quot;
        ///                   ManagementSoftwareManufacturer=&quot;Topcon Precision Agriculture&quot;
        ///                   DataTransferOrigin=&quot;2&quot;
        ///                   ManagementSoftwareVersion=&quot;1.0&quot;
        ///                   TaskControllerManufacturer=&quot;&quot;
        ///                   VersionMajor=&quot;4&quot; &gt;
        ///
        ///  &lt;XFR A=&quot;FRM00004&quot; B=&quot;1&quot; /&gt;
        ///
        ///  &lt;FRM A=&quot;FRM2&quot; B=&quot;Farm2&quot; C=&quot;Street2&quot; D=&quot;PO Box2&quot; E=&quot;PostalCode2&quot; F=&quot;City2&quot; G=&quot;State2&quot; H= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Farm4 {
            get {
                return ResourceManager.GetString("Farm4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;ISO11783_TaskData TaskControllerVersion=&quot;&quot;
        ///                   VersionMinor=&quot;1&quot;
        ///                   ManagementSoftwareManufacturer=&quot;Topcon Precision Agriculture&quot;
        ///                   DataTransferOrigin=&quot;2&quot;
        ///                   ManagementSoftwareVersion=&quot;1.0&quot;
        ///                   TaskControllerManufacturer=&quot;&quot;
        ///                   VersionMajor=&quot;4&quot; &gt;
        ///
        ///  &lt;FRM A=&quot;FRM1&quot; /&gt;
        ///
        ///&lt;/ISO11783_TaskData&gt;.
        /// </summary>
        internal static string Farm5 {
            get {
                return ResourceManager.GetString("Farm5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;ISO11783_TaskData TaskControllerVersion=&quot;&quot;
        ///                   VersionMinor=&quot;1&quot;
        ///                   ManagementSoftwareManufacturer=&quot;Topcon Precision Agriculture&quot;
        ///                   DataTransferOrigin=&quot;2&quot;
        ///                   ManagementSoftwareVersion=&quot;1.0&quot;
        ///                   TaskControllerManufacturer=&quot;&quot;
        ///                   VersionMajor=&quot;4&quot; &gt;
        ///
        ///  &lt;FRM B=&quot;Farm&quot; /&gt;
        ///
        ///&lt;/ISO11783_TaskData&gt;.
        /// </summary>
        internal static string Farm6 {
            get {
                return ResourceManager.GetString("Farm6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;ISO11783_TaskData TaskControllerVersion=&quot;&quot;
        ///                   VersionMinor=&quot;1&quot;
        ///                   ManagementSoftwareManufacturer=&quot;Topcon Precision Agriculture&quot;
        ///                   DataTransferOrigin=&quot;2&quot;
        ///                   ManagementSoftwareVersion=&quot;1.0&quot;
        ///                   TaskControllerManufacturer=&quot;&quot;
        ///                   VersionMajor=&quot;4&quot; &gt;
        ///
        ///  &lt;XFR A=&quot;FRM00007&quot; B=&quot;1&quot; /&gt;
        ///
        ///  &lt;/ISO11783_TaskData&gt;.
        /// </summary>
        internal static string Farm7 {
            get {
                return ResourceManager.GetString("Farm7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;ISO11783_TaskData TaskControllerVersion=&quot;&quot;
        ///                   VersionMinor=&quot;1&quot;
        ///                   ManagementSoftwareManufacturer=&quot;Topcon Precision Agriculture&quot;
        ///                   DataTransferOrigin=&quot;2&quot;
        ///                   ManagementSoftwareVersion=&quot;1.0&quot;
        ///                   TaskControllerManufacturer=&quot;&quot;
        ///                   VersionMajor=&quot;4&quot; &gt;
        ///
        ///  &lt;FRM A=&quot;FRM1&quot; B=&quot;Farm 1&quot; /&gt;
        ///  &lt;CTP A=&quot;CTP1&quot; B=&quot;Crop 1&quot; /&gt;
        ///  
        ///  &lt;PFD A=&quot;PFD1&quot; C=&quot;Field 1&quot; B=&quot;Field code 1&quot; D=&quot;12345&quot;  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Field1 {
            get {
                return ResourceManager.GetString("Field1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;ISO11783_TaskData TaskControllerVersion=&quot;&quot;
        ///                   VersionMinor=&quot;1&quot;
        ///                   ManagementSoftwareManufacturer=&quot;Topcon Precision Agriculture&quot;
        ///                   DataTransferOrigin=&quot;2&quot;
        ///                   ManagementSoftwareVersion=&quot;1.0&quot;
        ///                   TaskControllerManufacturer=&quot;&quot;
        ///                   VersionMajor=&quot;4&quot; &gt;
        ///
        ///  &lt;XFR A=&quot;PFD00010&quot; B=&quot;1&quot; /&gt;
        ///
        ///&lt;/ISO11783_TaskData&gt;.
        /// </summary>
        internal static string Field10 {
            get {
                return ResourceManager.GetString("Field10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;ISO11783_TaskData TaskControllerVersion=&quot;&quot;
        ///                   VersionMinor=&quot;1&quot;
        ///                   ManagementSoftwareManufacturer=&quot;Topcon Precision Agriculture&quot;
        ///                   DataTransferOrigin=&quot;2&quot;
        ///                   ManagementSoftwareVersion=&quot;1.0&quot;
        ///                   TaskControllerManufacturer=&quot;&quot;
        ///                   VersionMajor=&quot;4&quot; &gt;
        ///
        ///  &lt;FRM A=&quot;FRM1&quot; B=&quot;Farm 1&quot; /&gt;
        ///  &lt;CTP A=&quot;CTP1&quot; B=&quot;Crop 1&quot; /&gt;
        ///  
        ///  &lt;PFD A=&quot;PFD1&quot; C=&quot;Field 1&quot; B=&quot;Field code 1&quot; D=&quot;12345&quot;  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Field11 {
            get {
                return ResourceManager.GetString("Field11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;ISO11783_TaskData TaskControllerVersion=&quot;&quot;
        ///                   VersionMinor=&quot;1&quot;
        ///                   ManagementSoftwareManufacturer=&quot;Topcon Precision Agriculture&quot;
        ///                   DataTransferOrigin=&quot;2&quot;
        ///                   ManagementSoftwareVersion=&quot;1.0&quot;
        ///                   TaskControllerManufacturer=&quot;&quot;
        ///                   VersionMajor=&quot;4&quot; &gt;
        ///
        ///  &lt;FRM A=&quot;FRM1&quot; B=&quot;Farm 1&quot; /&gt;
        ///  &lt;CTP A=&quot;CTP1&quot; B=&quot;Crop 1&quot; /&gt;
        ///  
        ///  &lt;PFD A=&quot;PFD1&quot; C=&quot;Field 1&quot; B=&quot;Field code 1&quot; D=&quot;12345&quot;  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Field12 {
            get {
                return ResourceManager.GetString("Field12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;ISO11783_TaskData TaskControllerVersion=&quot;&quot;
        ///                   VersionMinor=&quot;1&quot;
        ///                   ManagementSoftwareManufacturer=&quot;Topcon Precision Agriculture&quot;
        ///                   DataTransferOrigin=&quot;2&quot;
        ///                   ManagementSoftwareVersion=&quot;1.0&quot;
        ///                   TaskControllerManufacturer=&quot;&quot;
        ///                   VersionMajor=&quot;4&quot; &gt;
        ///
        ///  &lt;FRM A=&quot;FRM1&quot; B=&quot;Farm 1&quot; /&gt;
        ///  &lt;CTP A=&quot;CTP1&quot; B=&quot;Crop 1&quot; /&gt;
        ///  
        ///  &lt;PFD A=&quot;PFD1&quot; C=&quot;Field 1&quot; B=&quot;Field code 1&quot; D=&quot;12345&quot;  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Field3 {
            get {
                return ResourceManager.GetString("Field3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;ISO11783_TaskData TaskControllerVersion=&quot;&quot;
        ///                   VersionMinor=&quot;1&quot;
        ///                   ManagementSoftwareManufacturer=&quot;Topcon Precision Agriculture&quot;
        ///                   DataTransferOrigin=&quot;2&quot;
        ///                   ManagementSoftwareVersion=&quot;1.0&quot;
        ///                   TaskControllerManufacturer=&quot;&quot;
        ///                   VersionMajor=&quot;4&quot; &gt;
        ///
        ///  &lt;FRM A=&quot;FRM1&quot; B=&quot;Farm 1&quot; /&gt;
        ///  &lt;CTP A=&quot;CTP1&quot; B=&quot;Crop 1&quot; /&gt;
        ///
        ///  &lt;PFD A=&quot;PFD1&quot; C=&quot;Field 1&quot; B=&quot;Field code 1&quot; D=&quot;12345&quot; F= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Field5 {
            get {
                return ResourceManager.GetString("Field5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;ISO11783_TaskData TaskControllerVersion=&quot;&quot;
        ///                   VersionMinor=&quot;1&quot;
        ///                   ManagementSoftwareManufacturer=&quot;Topcon Precision Agriculture&quot;
        ///                   DataTransferOrigin=&quot;2&quot;
        ///                   ManagementSoftwareVersion=&quot;1.0&quot;
        ///                   TaskControllerManufacturer=&quot;&quot;
        ///                   VersionMajor=&quot;4&quot; &gt;
        ///
        ///  &lt;FRM A=&quot;FRM1&quot; B=&quot;Farm 1&quot; /&gt;
        ///  &lt;CTP A=&quot;CTP1&quot; B=&quot;Crop 1&quot; /&gt;
        ///
        ///  &lt;PFD A=&quot;PFD1&quot; C=&quot;Field 1&quot; B=&quot;Field code 1&quot; D=&quot;12345&quot; F= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Field6 {
            get {
                return ResourceManager.GetString("Field6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;ISO11783_TaskData TaskControllerVersion=&quot;&quot;
        ///                   VersionMinor=&quot;1&quot;
        ///                   ManagementSoftwareManufacturer=&quot;Topcon Precision Agriculture&quot;
        ///                   DataTransferOrigin=&quot;2&quot;
        ///                   ManagementSoftwareVersion=&quot;1.0&quot;
        ///                   TaskControllerManufacturer=&quot;&quot;
        ///                   VersionMajor=&quot;4&quot; &gt;
        ///
        ///  &lt;PFD A=&quot;PFD1&quot; D=&quot;12345&quot; /&gt;
        ///
        ///&lt;/ISO11783_TaskData&gt;.
        /// </summary>
        internal static string Field7 {
            get {
                return ResourceManager.GetString("Field7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;ISO11783_TaskData TaskControllerVersion=&quot;&quot;
        ///                   VersionMinor=&quot;1&quot;
        ///                   ManagementSoftwareManufacturer=&quot;Topcon Precision Agriculture&quot;
        ///                   DataTransferOrigin=&quot;2&quot;
        ///                   ManagementSoftwareVersion=&quot;1.0&quot;
        ///                   TaskControllerManufacturer=&quot;&quot;
        ///                   VersionMajor=&quot;4&quot; &gt;
        ///
        ///  &lt;PFD A=&quot;PFD1&quot; C=&quot;12345&quot; /&gt;
        ///
        ///&lt;/ISO11783_TaskData&gt;.
        /// </summary>
        internal static string Field8 {
            get {
                return ResourceManager.GetString("Field8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;ISO11783_TaskData TaskControllerVersion=&quot;&quot;
        ///                   VersionMinor=&quot;1&quot;
        ///                   ManagementSoftwareManufacturer=&quot;Topcon Precision Agriculture&quot;
        ///                   DataTransferOrigin=&quot;2&quot;
        ///                   ManagementSoftwareVersion=&quot;1.0&quot;
        ///                   TaskControllerManufacturer=&quot;&quot;
        ///                   VersionMajor=&quot;4&quot; &gt;
        ///
        ///  &lt;PFD B=&quot;12345&quot; /&gt;
        ///
        ///&lt;/ISO11783_TaskData&gt;.
        /// </summary>
        internal static string Field9 {
            get {
                return ResourceManager.GetString("Field9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;XFC&gt;
        ///  &lt;FRM A=&quot;FRM1&quot; B=&quot;Farm1&quot; C=&quot;Street1&quot; D=&quot;PO Box1&quot; E=&quot;PostalCode1&quot; F=&quot;City1&quot; G=&quot;State1&quot; H=&quot;Country1&quot; I=&quot;CTR1&quot;/&gt;
        ///&lt;/XFC&gt;.
        /// </summary>
        internal static string FRM00004 {
            get {
                return ResourceManager.GetString("FRM00004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GroupsNoPatternsOrBoundary {
            get {
                object obj = ResourceManager.GetObject("GroupsNoPatternsOrBoundary", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ISO11783_TaskData VersionMajor=&quot;4&quot; VersionMinor=&quot;0&quot; ManagementSoftwareManufacturer=&quot;AgGateway&quot; ManagementSoftwareVersion=&quot;1.0&quot; DataTransferOrigin=&quot;1&quot; TaskControllerManufacturer=&quot;&quot; TaskControllerVersion=&quot;&quot;&gt;
        ///  &lt;PFD A=&quot;PFD0&quot; C=&quot;Field&quot; D=&quot;0&quot;&gt;
        ///    &lt;GGP A=&quot;GGP0&quot; B=&quot;guidance group 1&quot; /&gt;
        ///    &lt;GGP A=&quot;GGP1&quot; B=&quot;guidance group 2&quot; /&gt;
        ///    &lt;GGP A=&quot;GGP2&quot; B=&quot;guidance group 3&quot; /&gt;
        ///  &lt;/PFD&gt;
        ///&lt;/ISO11783_TaskData&gt;.
        /// </summary>
        internal static string GroupsNoPatternsOrBoundaryOutput {
            get {
                return ResourceManager.GetString("GroupsNoPatternsOrBoundaryOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GroupsWithBoundaryAndNoPatterns {
            get {
                object obj = ResourceManager.GetObject("GroupsWithBoundaryAndNoPatterns", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ISO11783_TaskData VersionMajor=&quot;4&quot; VersionMinor=&quot;0&quot; ManagementSoftwareManufacturer=&quot;AgGateway&quot; ManagementSoftwareVersion=&quot;1.0&quot; DataTransferOrigin=&quot;1&quot; TaskControllerManufacturer=&quot;&quot; TaskControllerVersion=&quot;&quot;&gt;
        ///  &lt;PFD A=&quot;PFD0&quot; C=&quot;Field&quot; D=&quot;0&quot;&gt;
        ///    &lt;GGP A=&quot;GGP0&quot; B=&quot;guidance group 1&quot;&gt;
        ///      &lt;PLN A=&quot;1&quot;&gt;
        ///        &lt;LSG A=&quot;1&quot;&gt;
        ///          &lt;PNT A=&quot;2&quot; B=&quot;start&quot; C=&quot;2&quot; D=&quot;1&quot; /&gt;
        ///        &lt;/LSG&gt;
        ///      &lt;/PLN&gt;
        ///    &lt;/GGP&gt;
        ///    &lt;GGP A=&quot;GGP1&quot; B=&quot;guidance group 2&quot;&gt;
        ///      &lt;PLN A=&quot;1&quot;&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GroupsWithBoundaryAndNoPatternsOutput {
            get {
                return ResourceManager.GetString("GroupsWithBoundaryAndNoPatternsOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GroupsWithBoundaryAndPatterns {
            get {
                object obj = ResourceManager.GetObject("GroupsWithBoundaryAndPatterns", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ISO11783_TaskData VersionMajor=&quot;4&quot; VersionMinor=&quot;0&quot; ManagementSoftwareManufacturer=&quot;AgGateway&quot; ManagementSoftwareVersion=&quot;1.0&quot; DataTransferOrigin=&quot;1&quot; TaskControllerManufacturer=&quot;&quot; TaskControllerVersion=&quot;&quot;&gt;
        ///  &lt;PFD A=&quot;PFD0&quot; C=&quot;Field&quot; D=&quot;0&quot;&gt;
        ///    &lt;GGP A=&quot;GGP0&quot; B=&quot;guidance group 1&quot;&gt;
        ///      &lt;GPN A=&quot;GPN0&quot; B=&quot;AbLine&quot; C=&quot;1&quot; E=&quot;1&quot;&gt;
        ///        &lt;LSG A=&quot;5&quot;&gt;
        ///          &lt;PNT A=&quot;2&quot; B=&quot;start&quot; C=&quot;2&quot; D=&quot;1&quot; /&gt;
        ///          &lt;PNT A=&quot;2&quot; B=&quot;end&quot; C=&quot;4&quot; D=&quot;3&quot; /&gt;
        ///        &lt;/LSG&gt;
        ///        &lt;PLN A= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GroupsWithBoundaryAndPatternsOutput {
            get {
                return ResourceManager.GetString("GroupsWithBoundaryAndPatternsOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MissingUnit {
            get {
                object obj = ResourceManager.GetObject("MissingUnit", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;TZN A=&quot;1&quot; B=&quot;zone1&quot;&gt;
        ///  &lt;PDV A=&quot;0006&quot; B=&quot;100&quot; C=&quot;PDT1&quot; /&gt;
        ///&lt;/TZN&gt;.
        /// </summary>
        internal static string MissingUnitOutput {
            get {
                return ResourceManager.GetString("MissingUnitOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MultipleVariables {
            get {
                object obj = ResourceManager.GetObject("MultipleVariables", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;TZN A=&quot;1&quot; B=&quot;zone1&quot;&gt;
        ///  &lt;PDV A=&quot;0006&quot; B=&quot;10000&quot; C=&quot;PDT1&quot; /&gt;
        ///  &lt;PDV A=&quot;0001&quot; B=&quot;2000000&quot; C=&quot;PDT2&quot; /&gt;
        ///  &lt;PDV A=&quot;0029&quot; B=&quot;300000&quot; C=&quot;PDT3&quot; /&gt;
        ///&lt;/TZN&gt;.
        /// </summary>
        internal static string MultipleVariablesOutput {
            get {
                return ResourceManager.GetString("MultipleVariablesOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] NoVariables {
            get {
                object obj = ResourceManager.GetObject("NoVariables", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;TZN A=&quot;1&quot; B=&quot;zone1&quot; /&gt;.
        /// </summary>
        internal static string NoVariablesOutput {
            get {
                return ResourceManager.GetString("NoVariablesOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] NoWorkersPresent {
            get {
                object obj = ResourceManager.GetObject("NoWorkersPresent", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;XFC&gt;
        ///  &lt;PDT A=&quot;PDT1&quot; B=&quot;Product 1&quot; E=&quot;0x0048&quot; F=&quot;2&quot; G=&quot;1000&quot;&gt;
        ///    &lt;PRN A=&quot;PDT2&quot; B=&quot;1000&quot; /&gt;
        ///  &lt;/PDT&gt;
        ///&lt;/XFC&gt;.
        /// </summary>
        internal static string PDT00002 {
            get {
                return ResourceManager.GetString("PDT00002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;XFC&gt;
        ///  &lt;PDT A=&quot;PDT2&quot; B=&quot;Product 2&quot; /&gt;
        ///&lt;/XFC&gt;.
        /// </summary>
        internal static string PDT00005 {
            get {
                return ResourceManager.GetString("PDT00005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;XFC&gt;
        ///  &lt;PFD A=&quot;PFD2&quot; C=&quot;Field 2&quot; B=&quot;Field code 2&quot; D=&quot;22345&quot; F=&quot;FRM1&quot;  G=&quot;CTP1&quot; I=&quot;PFD1&quot; /&gt;
        ///&lt;/XFC&gt;.
        /// </summary>
        internal static string PFD00006 {
            get {
                return ResourceManager.GetString("PFD00006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;XFC&gt;
        ///  &lt;PGP A=&quot;PGP1&quot; B=&quot;Group 1&quot; C=&quot;1&quot; /&gt;
        ///&lt;/XFC&gt;.
        /// </summary>
        internal static string PGP00001 {
            get {
                return ResourceManager.GetString("PGP00001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;XFC&gt;
        ///  &lt;PGP A=&quot;PGP2&quot; B=&quot;Group 2&quot; C=&quot;2&quot; /&gt;
        ///&lt;/XFC&gt;.
        /// </summary>
        internal static string PGP00002 {
            get {
                return ResourceManager.GetString("PGP00002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;ISO11783_TaskData TaskControllerVersion=&quot;&quot;
        ///                   VersionMinor=&quot;1&quot;
        ///                   ManagementSoftwareManufacturer=&quot;Topcon Precision Agriculture&quot;
        ///                   DataTransferOrigin=&quot;2&quot;
        ///                   ManagementSoftwareVersion=&quot;1.0&quot;
        ///                   TaskControllerManufacturer=&quot;&quot;
        ///                   VersionMajor=&quot;4&quot; &gt;
        ///
        ///  &lt;PDT A=&quot;PDT1&quot; B=&quot;Product 1&quot; E=&quot;0x0048&quot; F=&quot;1&quot; /&gt;
        ///  
        ///&lt;/ISO11783_TaskData&gt;.
        /// </summary>
        internal static string Product1 {
            get {
                return ResourceManager.GetString("Product1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;ISO11783_TaskData TaskControllerVersion=&quot;&quot;
        ///                   VersionMinor=&quot;1&quot;
        ///                   ManagementSoftwareManufacturer=&quot;Topcon Precision Agriculture&quot;
        ///                   DataTransferOrigin=&quot;2&quot;
        ///                   ManagementSoftwareVersion=&quot;1.0&quot;
        ///                   TaskControllerManufacturer=&quot;&quot;
        ///                   VersionMajor=&quot;4&quot; &gt;
        ///
        ///  &lt;PDT A=&quot;PDT1&quot; B=&quot;Product 1&quot; E=&quot;0x004B&quot; F=&quot;1&quot; /&gt;
        ///  
        ///&lt;/ISO11783_TaskData&gt;.
        /// </summary>
        internal static string Product2 {
            get {
                return ResourceManager.GetString("Product2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;ISO11783_TaskData TaskControllerVersion=&quot;&quot;
        ///                   VersionMinor=&quot;1&quot;
        ///                   ManagementSoftwareManufacturer=&quot;Topcon Precision Agriculture&quot;
        ///                   DataTransferOrigin=&quot;2&quot;
        ///                   ManagementSoftwareVersion=&quot;1.0&quot;
        ///                   TaskControllerManufacturer=&quot;&quot;
        ///                   VersionMajor=&quot;4&quot; &gt;
        ///
        ///  &lt;PDT A=&quot;PDT1&quot; B=&quot;Product 1&quot; E=&quot;0x004E&quot; F=&quot;1&quot; /&gt;
        ///  
        ///&lt;/ISO11783_TaskData&gt;.
        /// </summary>
        internal static string Product3 {
            get {
                return ResourceManager.GetString("Product3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;ISO11783_TaskData TaskControllerVersion=&quot;&quot;
        ///                   VersionMinor=&quot;1&quot;
        ///                   ManagementSoftwareManufacturer=&quot;Topcon Precision Agriculture&quot;
        ///                   DataTransferOrigin=&quot;2&quot;
        ///                   ManagementSoftwareVersion=&quot;1.0&quot;
        ///                   TaskControllerManufacturer=&quot;&quot;
        ///                   VersionMajor=&quot;4&quot; &gt;
        ///
        ///  &lt;PDT A=&quot;PDT1&quot; B=&quot;Product 1&quot; /&gt;  
        ///&lt;/ISO11783_TaskData&gt;.
        /// </summary>
        internal static string Product4 {
            get {
                return ResourceManager.GetString("Product4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;ISO11783_TaskData TaskControllerVersion=&quot;&quot;
        ///                   VersionMinor=&quot;1&quot;
        ///                   ManagementSoftwareManufacturer=&quot;Topcon Precision Agriculture&quot;
        ///                   DataTransferOrigin=&quot;2&quot;
        ///                   ManagementSoftwareVersion=&quot;1.0&quot;
        ///                   TaskControllerManufacturer=&quot;&quot;
        ///                   VersionMajor=&quot;4&quot; &gt;
        ///
        ///  &lt;PDT A=&quot;PDT1&quot; B=&quot;Product 1&quot; /&gt;
        ///
        ///  &lt;XFR A=&quot;PDT00005&quot; B=&quot;1&quot; /&gt;
        ///
        ///&lt;/ISO11783_TaskData&gt;.
        /// </summary>
        internal static string Product5 {
            get {
                return ResourceManager.GetString("Product5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;ISO11783_TaskData TaskControllerVersion=&quot;&quot;
        ///                   VersionMinor=&quot;1&quot;
        ///                   ManagementSoftwareManufacturer=&quot;Topcon Precision Agriculture&quot;
        ///                   DataTransferOrigin=&quot;2&quot;
        ///                   ManagementSoftwareVersion=&quot;1.0&quot;
        ///                   TaskControllerManufacturer=&quot;&quot;
        ///                   VersionMajor=&quot;4&quot; &gt;
        ///
        ///  &lt;PDT A=&quot;PDT1&quot; /&gt;
        ///  
        ///&lt;/ISO11783_TaskData&gt;.
        /// </summary>
        internal static string Product6 {
            get {
                return ResourceManager.GetString("Product6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;ISO11783_TaskData TaskControllerVersion=&quot;&quot;
        ///                   VersionMinor=&quot;1&quot;
        ///                   ManagementSoftwareManufacturer=&quot;Topcon Precision Agriculture&quot;
        ///                   DataTransferOrigin=&quot;2&quot;
        ///                   ManagementSoftwareVersion=&quot;1.0&quot;
        ///                   TaskControllerManufacturer=&quot;&quot;
        ///                   VersionMajor=&quot;4&quot; &gt;
        ///
        ///  &lt;PDT A=&quot;PDT1&quot; B=&quot;Product 1&quot; C=&quot;PGP1&quot;/&gt;
        ///  &lt;PGP A=&quot;PGP1&quot; B=&quot;Group 1&quot; C=&quot;1&quot; /&gt;
        ///
        ///  &lt;PDT A=&quot;PDT2&quot; B=&quot;Product 2&quot; C=&quot;PGP2&quot;/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Product7 {
            get {
                return ResourceManager.GetString("Product7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;ISO11783_TaskData TaskControllerVersion=&quot;&quot;
        ///                   VersionMinor=&quot;1&quot;
        ///                   ManagementSoftwareManufacturer=&quot;Topcon Precision Agriculture&quot;
        ///                   DataTransferOrigin=&quot;2&quot;
        ///                   ManagementSoftwareVersion=&quot;1.0&quot;
        ///                   TaskControllerManufacturer=&quot;&quot;
        ///                   VersionMajor=&quot;4&quot; &gt;
        ///
        ///  &lt;PDT A=&quot;PDT1&quot; B=&quot;Product 1&quot;  E=&quot;4B&quot; F=&quot;1&quot; &gt;
        ///    &lt;PRN A=&quot;PDT2&quot; B=&quot;1000&quot; /&gt;
        ///  &lt;/PDT&gt;
        ///
        ///&lt;/ISO11783_TaskData&gt;.
        /// </summary>
        internal static string Product8 {
            get {
                return ResourceManager.GetString("Product8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;ISO11783_TaskData TaskControllerVersion=&quot;&quot;
        ///                   VersionMinor=&quot;1&quot;
        ///                   ManagementSoftwareManufacturer=&quot;Topcon Precision Agriculture&quot;
        ///                   DataTransferOrigin=&quot;2&quot;
        ///                   ManagementSoftwareVersion=&quot;1.0&quot;
        ///                   TaskControllerManufacturer=&quot;&quot;
        ///                   VersionMajor=&quot;4&quot; &gt;
        ///
        ///  &lt;PDT A=&quot;PDT1&quot; B=&quot;Product 1&quot; C=&quot;PGP1&quot;/&gt;
        ///  &lt;XFR A=&quot;PGP00001&quot; B=&quot;1&quot; /&gt;
        ///
        ///  &lt;PDT A=&quot;PDT2&quot; B=&quot;Product 2&quot; C=&quot;PGP2&quot;/&gt;
        ///  &lt;XF [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Product9 {
            get {
                return ResourceManager.GetString("Product9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;ISO11783_TaskData TaskControllerVersion=&quot;&quot;
        ///                   VersionMinor=&quot;1&quot;
        ///                   ManagementSoftwareManufacturer=&quot;Topcon Precision Agriculture&quot;
        ///                   DataTransferOrigin=&quot;2&quot;
        ///                   ManagementSoftwareVersion=&quot;1.0&quot;
        ///                   TaskControllerManufacturer=&quot;&quot;
        ///                   VersionMajor=&quot;4&quot; &gt;
        ///
        ///  &lt;PDT A=&quot;PDT1&quot; B=&quot;Product 1&quot; E=&quot;0x0048&quot; F=&quot;2&quot; G=&quot;1000&quot;&gt;
        ///    &lt;PRN A=&quot;PDT2&quot; B=&quot;1000&quot; /&gt;
        ///  &lt;/PDT&gt;
        ///
        ///  &lt;PDT A=&quot;PDT2&quot; B=&quot;P [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ProductMix1 {
            get {
                return ResourceManager.GetString("ProductMix1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;ISO11783_TaskData TaskControllerVersion=&quot;&quot;
        ///                   VersionMinor=&quot;1&quot;
        ///                   ManagementSoftwareManufacturer=&quot;Topcon Precision Agriculture&quot;
        ///                   DataTransferOrigin=&quot;2&quot;
        ///                   ManagementSoftwareVersion=&quot;1.0&quot;
        ///                   TaskControllerManufacturer=&quot;&quot;
        ///                   VersionMajor=&quot;4&quot; &gt;
        ///
        ///  &lt;XFR A=&quot;PDT00002&quot; B=&quot;1&quot; /&gt;
        ///
        ///  &lt;PDT A=&quot;PDT2&quot; B=&quot;Product 2&quot; E=&quot;48&quot; /&gt;
        ///
        ///&lt;/ISO11783_TaskData&gt;.
        /// </summary>
        internal static string ProductMix2 {
            get {
                return ResourceManager.GetString("ProductMix2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;ISO11783_TaskData TaskControllerVersion=&quot;&quot;
        ///                   VersionMinor=&quot;1&quot;
        ///                   ManagementSoftwareManufacturer=&quot;Topcon Precision Agriculture&quot;
        ///                   DataTransferOrigin=&quot;2&quot;
        ///                   ManagementSoftwareVersion=&quot;1.0&quot;
        ///                   TaskControllerManufacturer=&quot;&quot;
        ///                   VersionMajor=&quot;4&quot; &gt;
        ///
        ///  &lt;PDT A=&quot;PDT1&quot; B=&quot;Product 1&quot; E=&quot;0x0048&quot; F=&quot;2&quot;&gt;
        ///    &lt;PRN A=&quot;PDT2&quot; B=&quot;1000&quot; /&gt;
        ///  &lt;/PDT&gt;
        ///
        ///&lt;/ISO11783_TaskData&gt;.
        /// </summary>
        internal static string ProductMix3 {
            get {
                return ResourceManager.GetString("ProductMix3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;ISO11783_TaskData TaskControllerVersion=&quot;&quot;
        ///                   VersionMinor=&quot;1&quot;
        ///                   ManagementSoftwareManufacturer=&quot;Topcon Precision Agriculture&quot;
        ///                   DataTransferOrigin=&quot;2&quot;
        ///                   ManagementSoftwareVersion=&quot;1.0&quot;
        ///                   TaskControllerManufacturer=&quot;&quot;
        ///                   VersionMajor=&quot;4&quot; &gt;
        ///
        ///  &lt;PDT A=&quot;PDT1&quot; B=&quot;Product 1&quot; E=&quot;0x0048&quot; F=&quot;1&quot;&gt;
        ///    &lt;PRN A=&quot;PDT2&quot; B=&quot;1000&quot; /&gt;
        ///  &lt;/PDT&gt;
        ///
        ///  &lt;PDT A=&quot;PDT2&quot; B=&quot;Product 2&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ProductMix4 {
            get {
                return ResourceManager.GetString("ProductMix4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SingleProduct {
            get {
                object obj = ResourceManager.GetObject("SingleProduct", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 010000000200000003000000040000000500000006000000070000000800000009000000.
        /// </summary>
        internal static string SingleProductOutputTxt {
            get {
                return ResourceManager.GetString("SingleProductOutputTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ISO11783_TaskData VersionMajor=&quot;4&quot; VersionMinor=&quot;0&quot; ManagementSoftwareManufacturer=&quot;AgGateway&quot; ManagementSoftwareVersion=&quot;1.0&quot; DataTransferOrigin=&quot;1&quot; TaskControllerManufacturer=&quot;&quot; TaskControllerVersion=&quot;&quot;&gt;
        ///  &lt;PDT A=&quot;PDT0&quot; B=&quot;product&quot; /&gt;
        ///  &lt;TSK A=&quot;TSK0&quot; B=&quot;test&quot; G=&quot;1&quot;&gt;
        ///    &lt;TZN A=&quot;1&quot; B=&quot;Default&quot;&gt;
        ///      &lt;PDV A=&quot;0006&quot; B=&quot;0&quot; C=&quot;PDT0&quot; /&gt;
        ///    &lt;/TZN&gt;
        ///    &lt;GRD A=&quot;2&quot; B=&quot;1&quot; C=&quot;0.00020000000000&quot; D=&quot;0.00010000000000&quot; E=&quot;3&quot; F=&quot;3&quot; G=&quot;GRD00000&quot; I=&quot;2&quot; J=&quot;1&quot; /&gt;
        ///  &lt;/TSK&gt;
        ///&lt;/ISO [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SingleProductOutputXml {
            get {
                return ResourceManager.GetString("SingleProductOutputXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;ISO11783_TaskData TaskControllerVersion=&quot;&quot;
        ///                   VersionMinor=&quot;1&quot;
        ///                   ManagementSoftwareManufacturer=&quot;Topcon Precision Agriculture&quot;
        ///                   DataTransferOrigin=&quot;2&quot;
        ///                   ManagementSoftwareVersion=&quot;1.0&quot;
        ///                   TaskControllerManufacturer=&quot;&quot;
        ///                   VersionMajor=&quot;4&quot; &gt;
        ///
        ///  &lt;ASP A=&quot;2016-02-02T14:01:01.111Z&quot; D=&quot;1&quot;&gt;
        ///  &lt;/ASP&gt;  
        ///  
        ///&lt;/ISO11783_TaskData&gt;.
        /// </summary>
        internal static string Timestamp1 {
            get {
                return ResourceManager.GetString("Timestamp1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;ISO11783_TaskData TaskControllerVersion=&quot;&quot;
        ///                   VersionMinor=&quot;1&quot;
        ///                   ManagementSoftwareManufacturer=&quot;Topcon Precision Agriculture&quot;
        ///                   DataTransferOrigin=&quot;2&quot;
        ///                   ManagementSoftwareVersion=&quot;1.0&quot;
        ///                   TaskControllerManufacturer=&quot;&quot;
        ///                   VersionMajor=&quot;4&quot; &gt;
        ///
        ///  &lt;ASP A=&quot;2016-02-02T14:01:01.111Z&quot; C=&quot;1000&quot; D=&quot;1&quot;&gt;
        ///  &lt;/ASP&gt;  
        ///  
        ///&lt;/ISO11783_TaskData&gt;.
        /// </summary>
        internal static string Timestamp2 {
            get {
                return ResourceManager.GetString("Timestamp2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;ISO11783_TaskData TaskControllerVersion=&quot;&quot;
        ///                   VersionMinor=&quot;1&quot;
        ///                   ManagementSoftwareManufacturer=&quot;Topcon Precision Agriculture&quot;
        ///                   DataTransferOrigin=&quot;2&quot;
        ///                   ManagementSoftwareVersion=&quot;1.0&quot;
        ///                   TaskControllerManufacturer=&quot;&quot;
        ///                   VersionMajor=&quot;4&quot; &gt;
        ///
        ///  &lt;ASP A=&quot;2016-02-02T14:01:01.111Z&quot; B=&quot;2016-02-02T14:02:01.111Z&quot; D=&quot;1&quot;&gt;
        ///  &lt;/ASP&gt;  
        ///  
        ///&lt;/ISO11783_TaskData&gt;.
        /// </summary>
        internal static string Timestamp3 {
            get {
                return ResourceManager.GetString("Timestamp3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;ISO11783_TaskData TaskControllerVersion=&quot;&quot;
        ///                   VersionMinor=&quot;1&quot;
        ///                   ManagementSoftwareManufacturer=&quot;Topcon Precision Agriculture&quot;
        ///                   DataTransferOrigin=&quot;2&quot;
        ///                   ManagementSoftwareVersion=&quot;1.0&quot;
        ///                   TaskControllerManufacturer=&quot;&quot;
        ///                   VersionMajor=&quot;4&quot; &gt;
        ///
        ///  &lt;ASP A=&quot;2016-02-02T14:01:01.111Z&quot; B=&quot;2016-02-02T14:02:01.111Z&quot; D=&quot;4&quot;&gt;
        ///  &lt;/ASP&gt;  
        ///  
        ///&lt;/ISO11783_TaskData&gt;.
        /// </summary>
        internal static string Timestamp4 {
            get {
                return ResourceManager.GetString("Timestamp4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;ISO11783_TaskData TaskControllerVersion=&quot;&quot;
        ///                   VersionMinor=&quot;1&quot;
        ///                   ManagementSoftwareManufacturer=&quot;Topcon Precision Agriculture&quot;
        ///                   DataTransferOrigin=&quot;2&quot;
        ///                   ManagementSoftwareVersion=&quot;1.0&quot;
        ///                   TaskControllerManufacturer=&quot;&quot;
        ///                   VersionMajor=&quot;4&quot; &gt;
        ///
        ///  &lt;TestCase name=&quot;missing start attribute&quot;&gt;
        ///    &lt;ASP D=&quot;1&quot;&gt;
        ///    &lt;/ASP&gt;
        ///  &lt;/TestCase&gt;
        ///
        ///  &lt;TestCase name=&quot;missing type [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Timestamp5 {
            get {
                return ResourceManager.GetString("Timestamp5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;ISO11783_TaskData TaskControllerVersion=&quot;&quot;
        ///                   VersionMinor=&quot;1&quot;
        ///                   ManagementSoftwareManufacturer=&quot;Topcon Precision Agriculture&quot;
        ///                   DataTransferOrigin=&quot;2&quot;
        ///                   ManagementSoftwareVersion=&quot;1.0&quot;
        ///                   TaskControllerManufacturer=&quot;&quot;
        ///                   VersionMajor=&quot;4&quot; &gt;
        ///
        ///  &lt;ASP A=&quot;2016-02-02T14:01:01.111Z&quot; D=&quot;1&quot;&gt;
        ///    &lt;PTN A=&quot;54.588945&quot; B=&quot;9.989209&quot; D=&quot;3&quot; G=&quot;2&quot; H=&quot;10000&quot; I=&quot;500&quot; /&gt;
        ///  &lt;/ASP [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Timestamp6 {
            get {
                return ResourceManager.GetString("Timestamp6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;ISO11783_TaskData TaskControllerVersion=&quot;&quot;
        ///                   VersionMinor=&quot;1&quot;
        ///                   ManagementSoftwareManufacturer=&quot;Topcon Precision Agriculture&quot;
        ///                   DataTransferOrigin=&quot;2&quot;
        ///                   ManagementSoftwareVersion=&quot;1.0&quot;
        ///                   TaskControllerManufacturer=&quot;&quot;
        ///                   VersionMajor=&quot;4&quot; &gt;
        ///
        ///  &lt;TestCase name=&quot;missing east position attribute&quot;&gt;
        ///    &lt;ASP A=&quot;2016-02-02T14:01:01.111Z&quot; D=&quot;1&quot;&gt;
        ///      &lt;PTN A=&quot;54.58894 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Timestamp7 {
            get {
                return ResourceManager.GetString("Timestamp7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;ISO11783_TaskData TaskControllerVersion=&quot;&quot;
        ///                   VersionMinor=&quot;1&quot;
        ///                   ManagementSoftwareManufacturer=&quot;Topcon Precision Agriculture&quot;
        ///                   DataTransferOrigin=&quot;2&quot;
        ///                   ManagementSoftwareVersion=&quot;1.0&quot;
        ///                   TaskControllerManufacturer=&quot;&quot;
        ///                   VersionMajor=&quot;4&quot; &gt;
        ///
        ///  &lt;TestCase name=&quot;missing gps date attribute&quot;&gt;
        ///    &lt;ASP A=&quot;2016-02-02T14:01:01.111Z&quot; D=&quot;1&quot;&gt;
        ///      &lt;PTN A=&quot;54.588945&quot; B= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Timestamp8 {
            get {
                return ResourceManager.GetString("Timestamp8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] UnsupportedUnitDimension {
            get {
                object obj = ResourceManager.GetObject("UnsupportedUnitDimension", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;TZN A=&quot;1&quot; B=&quot;zone1&quot;&gt;
        ///  &lt;PDV A=&quot;0006&quot; B=&quot;10000&quot; C=&quot;PDT1&quot; /&gt;
        ///&lt;/TZN&gt;.
        /// </summary>
        internal static string UnsupportedUnitDimensionOutput {
            get {
                return ResourceManager.GetString("UnsupportedUnitDimensionOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] WorkersWithAllData {
            get {
                object obj = ResourceManager.GetObject("WorkersWithAllData", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ISO11783_TaskData VersionMajor=&quot;4&quot; VersionMinor=&quot;0&quot; ManagementSoftwareManufacturer=&quot;AgGateway&quot; ManagementSoftwareVersion=&quot;1.0&quot; DataTransferOrigin=&quot;1&quot; TaskControllerManufacturer=&quot;&quot; TaskControllerVersion=&quot;&quot;&gt;
        ///  &lt;WKR A=&quot;WKR0&quot; B=&quot;last&quot; C=&quot;first&quot; D=&quot;line&quot; E=&quot;po box&quot; F=&quot;postal code&quot; G=&quot;city&quot; H=&quot;state&quot; I=&quot;country&quot; J=&quot;Fixed&quot; K=&quot;Mobile&quot; L=&quot;Fax&quot; M=&quot;Email&quot; /&gt;
        ///  &lt;WKR A=&quot;WKR1&quot; B=&quot;last2&quot; C=&quot;first2&quot; D=&quot;line2&quot; E=&quot;po box2&quot; F=&quot;postal code2&quot; G=&quot;city2&quot; H=&quot;state2&quot; I=&quot;country2&quot; J=&quot;Fixed2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WorkersWithAllDataOutput {
            get {
                return ResourceManager.GetString("WorkersWithAllDataOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] WorkersWithNoContacts {
            get {
                object obj = ResourceManager.GetObject("WorkersWithNoContacts", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ISO11783_TaskData VersionMajor=&quot;4&quot; VersionMinor=&quot;0&quot; ManagementSoftwareManufacturer=&quot;AgGateway&quot; ManagementSoftwareVersion=&quot;1.0&quot; DataTransferOrigin=&quot;1&quot; TaskControllerManufacturer=&quot;&quot; TaskControllerVersion=&quot;&quot;&gt;
        ///  &lt;WKR A=&quot;WKR0&quot; B=&quot;last&quot; C=&quot;first&quot; /&gt;
        ///  &lt;WKR A=&quot;WKR1&quot; B=&quot;last2&quot; C=&quot;first2&quot; /&gt;
        ///  &lt;WKR A=&quot;WKR2&quot; B=&quot;last3&quot; C=&quot;first3&quot; /&gt;
        ///&lt;/ISO11783_TaskData&gt;.
        /// </summary>
        internal static string WorkersWithNoContactsOutput {
            get {
                return ResourceManager.GetString("WorkersWithNoContactsOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ZeroWorkersPresent {
            get {
                object obj = ResourceManager.GetObject("ZeroWorkersPresent", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
