name: CI

on: 
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK '3.1'
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: '3.1'
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build ./ISOv4Plugin/ISOv4Plugin.csproj -c Release -f netstandard2.0 --no-restore