name: CI

on: 
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.6
      - name: Setup .NET Core SDK '8.0'
        uses: actions/setup-dotnet@v4.0.0
        with:
          dotnet-version: '8.0'
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build ./ISOv4Plugin/ISOv4Plugin.csproj -c Release -f netstandard2.0 --no-restore